from rdflib import URIRef

triples_map_uri = URIRef("http://example.com/base/TriplesMap1")
logical_source_uri = URIRef('http://semweb.mmlab.be/ns/rml#logicalSource')
subject_map_uri = URIRef('http://www.w3.org/ns/r2rml#subjectMap')
predicate_map_uri = URIRef('http://www.w3.org/ns/r2rml#predicateObjectMap')
rml_reference_uri = URIRef('http://semweb.mmlab.be/ns/rml#reference')
typing_uri = URIRef('http://semweb.mmlab.be/ns/rml#referenceFormulation')
template_uri = URIRef("http://www.w3.org/ns/r2rml#template")
class_uri = URIRef("http://www.w3.org/ns/r2rml#class")
term_type_uri = URIRef("http://www.w3.org/ns/r2rml#termType")
reference_uri = URIRef('http://semweb.mmlab.be/ns/rml#reference')
source_uri = URIRef('http://semweb.mmlab.be/ns/rml#source')
iterator_uri = URIRef("http://semweb.mmlab.be/ns/rml#iterator")
predicate_uri = URIRef('http://www.w3.org/ns/r2rml#predicate')
object_map_uri = URIRef('http://www.w3.org/ns/r2rml#objectMap')
object_uri = URIRef('http://www.w3.org/ns/r2rml#object')
